### PR TITLE
Add save method

### PR DESCRIPTION
**Pull request by Freyskeyd**
Add a save method which accept a regex to save some variables when using the empty method.

Signed-off-by: Freyskeyd <simon.paitrault@gmail.com>

### CODE REVIEW

**Comment by Freyskeyd** [comment]
ping @killercup and @epage for issue killercup/assert_cli#51

**Comment by killercup** [comment]
If this is only for killercup/assert_cli#51, I'd rather do it like killercup/assert_cli#54. But this feature has its own merits.

I'd not call it `save`, though. Maybe `recover`?

**Comment by Freyskeyd** [comment]
Yeah, I think this is a feature needed outside of assert_cli.

I was divide about the name.

- save
- recover
- keep

What do you think?

**Comment by killercup** [comment]
So, the starting point is an empty env, and we are copying the parent scope's env var.

Maybe `inherit_var`?

**Comment by Freyskeyd** [comment]
why not:

```rust
let env = Environment::empty()
    .inherit_vars("^CARGO_.*")
    .insert("CARGO_SOMETHING", "ok");
```

We can also:

```rust
let env = Environment::inherit_matches("^CARGO_*")
    .insert("CARGO_SOMETHING", "ok");

**Comment by epage** [comment]
I agree about `inherit` for the base name.

For consistency, a `inherit_vars` should probably take an iterator.  We could do some `From` stuff so it assumes a string is a regex, though I tend to prefer things more explicit.  I like `inherit_matches` for that reason

So overall, I'd like to see
- `inherit_var`
- `inherit_vars`
- `inherit_matches`

Question: If clients do not need `inherit_matches`, should we force a regex dependency on them?  Should it be a feature (default or not) so users can better control their compile times?

**Pull request closed without merging**
